import {useEffect,useState} from 'react';
import {NavLink,Navigate,Route,Routes,useNavigate} from 'react-router-dom';
import {api} from './api';
import {Bot,FileText,Gauge,LogOut,MessageSquare,Shield,UploadCloud,UserRound} from 'lucide-react';

type Doc={id:string;original_filename:string;file_type:string;file_size:number;processing_status:string;page_count:number|null;chunk_count:number;processing_error:string|null;created_at:string};
type Source={document_id:string;filename:string;page_number:number|null;chunk_id:string;score:number|null};
type Conversation={id:string;title:string;created_at:string;updated_at:string};
const loggedIn=()=>!!localStorage.getItem('token');

function Protected({children}:{children:React.ReactNode}){return loggedIn()?<>{children}</>:<Navigate to="/login" replace/>}
function Shell({children}:{children:React.ReactNode}){const nav=useNavigate(); const links=[['/dashboard','Dashboard',Gauge],['/documents','Documents',FileText],['/chat','Chat',MessageSquare],['/conversations','History',Bot],['/profile','Profile',UserRound],['/admin','Admin',Shield]] as const; return <div className="min-h-screen bg-slate-50 flex"><aside className="w-64 bg-slate-950 text-slate-200 p-5 fixed inset-y-0"><div className="text-xl font-bold text-white mb-8">Enterprise<span className="text-cyan-400">RAG</span></div><nav className="space-y-1">{links.map(([p,l,I])=><NavLink key={p} to={p} className={({isActive})=>`flex items-center gap-3 px-3 py-2.5 rounded-xl ${isActive?'bg-cyan-500 text-slate-950 font-semibold':'hover:bg-slate-900'}`}><I size={18}/>{l}</NavLink>)}</nav><button onClick={()=>{localStorage.removeItem('token');nav('/login')}} className="absolute bottom-5 left-5 flex items-center gap-2 text-slate-400 hover:text-white"><LogOut size={17}/>Logout</button></aside><main className="ml-64 flex-1 p-8 max-w-[1500px]">{children}</main></div>}
function Auth({mode}:{mode:'login'|'register'}){const nav=useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); async function submit(e:React.FormEvent){e.preventDefault();setError('');try{if(mode==='register') await api.post('/auth/register',{email,password});const r=await api.post('/auth/login',{email,password});localStorage.setItem('token',r.data.access_token);nav('/dashboard')}catch(e:any){setError(e.response?.data?.detail||'Request failed')}}return <div className="min-h-screen grid place-items-center bg-gradient-to-br from-slate-950 via-slate-900 to-cyan-950 p-6"><form onSubmit={submit} className="w-full max-w-md card p-8"><div className="text-2xl font-bold mb-2">{mode==='login'?'Welcome back':'Create your workspace'}</div><p className="text-slate-500 mb-6">Secure enterprise document intelligence.</p><label className="text-sm font-medium">Email</label><input className="w-full border rounded-xl p-3 mt-1 mb-4" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label className="text-sm font-medium">Password</label><input className="w-full border rounded-xl p-3 mt-1 mb-2" type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<p className="text-red-600 text-sm my-3">{error}</p>}<button className="w-full bg-slate-950 text-white rounded-xl p-3 mt-4 font-semibold">{mode==='login'?'Login':'Register & Login'}</button><button type="button" onClick={()=>nav(mode==='login'?'/register':'/login')} className="w-full mt-3 text-sm text-cyan-700">{mode==='login'?'Need an account? Register':'Already registered? Login'}</button></form></div>}
function Dashboard(){const [docs,setDocs]=useState<Doc[]>([]);const [convos,setConvos]=useState<Conversation[]>([]);useEffect(()=>{api.get('/documents').then(r=>setDocs(r.data));api.get('/conversations').then(r=>setConvos(r.data))},[]);const completed=docs.filter(d=>d.processing_status==='COMPLETED').length;const processing=docs.filter(d=>['UPLOADED','PROCESSING'].includes(d.processing_status)).length;const failed=docs.filter(d=>d.processing_status==='FAILED').length;return <Page title="Dashboard" subtitle="Your private document intelligence workspace"><div className="grid grid-cols-4 gap-4">{[['Documents',docs.length],['Ready',completed],['Processing',processing],['Failed',failed]].map(([l,v])=><div className="card p-5" key={l}><div className="text-slate-500 text-sm">{l}</div><div className="text-3xl font-bold mt-1">{v}</div></div>)}</div><div className="grid grid-cols-2 gap-6 mt-6"><div className="card p-6"><h3 className="font-semibold mb-4">Recent documents</h3>{docs.slice(0,5).map(d=><div className="py-2 border-b last:border-0 flex justify-between"><span>{d.original_filename}</span><Status s={d.processing_status}/></div>)}{!docs.length&&<Empty text="Upload your first document."/>}</div><div className="card p-6"><h3 className="font-semibold mb-4">Recent conversations</h3>{convos.slice(0,5).map(c=><div className="py-2 border-b last:border-0">{c.title}</div>)}{!convos.length&&<Empty text="Ask your first question."/>}</div></div></Page>}
function Documents(){const [docs,setDocs]=useState<Doc[]>([]);const [busy,setBusy]=useState(false);const load=()=>api.get('/documents').then(r=>setDocs(r.data));useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[]);async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setBusy(true);const data=new FormData();data.append('file',f);try{await api.post('/documents/upload',data);await load()}finally{setBusy(false);e.target.value=''}}async function del(id:string){if(confirm('Delete this document?')){await api.delete(`/documents/${id}`);load()}}return <Page title="Documents" subtitle="Upload PDFs, DOCX, TXT, or CSV. Processing runs asynchronously."><label className="card p-7 border-dashed border-2 flex items-center gap-4 cursor-pointer hover:border-cyan-500"><UploadCloud size={34}/><div><b>{busy?'Uploading...':'Upload a document'}</b><div className="text-sm text-slate-500">Maximum size is controlled by MAX_UPLOAD_SIZE.</div></div><input className="hidden" type="file" accept=".pdf,.docx,.txt,.csv" onChange={upload} disabled={busy}/></label><div className="card overflow-hidden mt-6"><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr>{['File','Type','Status','Pages','Chunks','Actions'].map(x=><th className="p-3">{x}</th>)}</tr></thead><tbody>{docs.map(d=><tr className="border-t"><td className="p-3 font-medium">{d.original_filename}{d.processing_error&&<div className="text-red-600 text-xs">{d.processing_error}</div>}</td><td className="p-3 uppercase">{d.file_type}</td><td className="p-3"><Status s={d.processing_status}/></td><td className="p-3">{d.page_count??'—'}</td><td className="p-3">{d.chunk_count}</td><td className="p-3"><button onClick={()=>del(d.id)} className="text-red-600">Delete</button></td></tr>)}</tbody></table>{!docs.length&&<Empty text="No documents yet."/>}</div></Page>}
function Chat(){const [q,setQ]=useState('');const [answer,setAnswer]=useState('');const [sources,setSources]=useState<Source[]>([]);const [loading,setLoading]=useState(false);const [cid,setCid]=useState<string|undefined>();async function ask(e:React.FormEvent){e.preventDefault();if(!q.trim())return;setLoading(true);setAnswer('');setSources([]);try{const r=await api.post('/chat',{question:q,conversation_id:cid});setCid(r.data.conversation_id);setAnswer(r.data.answer);setSources(r.data.sources)}catch(e:any){setAnswer(e.response?.data?.detail||'Request failed')}finally{setLoading(false)}}return <Page title="Chat" subtitle="Hybrid retrieval + reranking + multi-agent verification"><div className="card p-6 min-h-[430px]"><div className="text-sm text-slate-500 mb-4">{loading?'Searching your documents, ranking relevant sources, and generating an answer...':'Ask a grounded question about your documents.'}</div>{answer?<><div className="whitespace-pre-wrap leading-7">{answer}</div><div className="grid md:grid-cols-2 gap-3 mt-6">{sources.map((s,i)=><div className="border rounded-xl p-3" key={s.chunk_id}><div className="font-semibold text-sm">S{i+1} · {s.filename}</div><div className="text-xs text-slate-500 mt-1">Page {s.page_number??'N/A'} · Chunk {s.chunk_id.slice(0,8)}…</div></div>)}</div></>:<Empty text="Try: What is the annual leave policy?"/>}</div><form onSubmit={ask} className="mt-4 flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} className="flex-1 border rounded-xl p-4" placeholder="Ask a question..."/><button disabled={loading} className="bg-cyan-500 text-slate-950 font-semibold px-6 rounded-xl">Send</button></form></Page>}
function History(){const [items,setItems]=useState<Conversation[]>([]);useEffect(()=>{api.get('/conversations').then(r=>setItems(r.data))},[]);return <Page title="Conversation history" subtitle="Only your own conversations are visible"><div className="card p-4">{items.map(c=><div className="p-4 border-b last:border-0"><div className="font-semibold">{c.title}</div><div className="text-xs text-slate-500">{new Date(c.updated_at).toLocaleString()}</div></div>)}{!items.length&&<Empty text="No conversations yet."/>}</div></Page>}
function Profile(){const [me,setMe]=useState<any>();useEffect(()=>{api.get('/auth/me').then(r=>setMe(r.data))},[]);return <Page title="Profile" subtitle="Authentication and role information"><div className="card p-6 max-w-xl"><div className="text-sm text-slate-500">Email</div><div className="font-semibold mb-4">{me?.email||'Loading...'}</div><div className="text-sm text-slate-500">Role</div><div className="font-semibold">{me?.role||'—'}</div></div></Page>}
function Admin(){const [stats,setStats]=useState<any>();const [error,setError]=useState('');useEffect(()=>{api.get('/admin/stats').then(r=>setStats(r.data)).catch(e=>setError(e.response?.data?.detail||'Admin role required'))},[]);return <Page title="Admin" subtitle="System-wide metrics for administrators">{error?<div className="card p-6 text-amber-700">{error}</div>:<div className="grid grid-cols-3 gap-4">{stats&&Object.entries(stats).map(([k,v])=><div className="card p-5"><div className="text-sm text-slate-500">{k.replaceAll('_',' ')}</div><div className="text-2xl font-bold">{String(v)}</div></div>)}</div>}</Page>}
function Page({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <><header className="mb-7"><h1 className="text-3xl font-bold">{title}</h1><p className="text-slate-500 mt-1">{subtitle}</p></header>{children}</>}
function Empty({text}:{text:string}){return <div className="text-center text-slate-400 py-12">{text}</div>}
function Status({s}:{s:string}){const cls=s==='COMPLETED'?'bg-emerald-100 text-emerald-700':s==='FAILED'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700';return <span className={`px-2 py-1 rounded-full text-xs font-semibold ${cls}`}>{s}</span>}
export default function App(){return <Routes><Route path="/login" element={<Auth mode="login"/>}/><Route path="/register" element={<Auth mode="register"/>}/>{[['/dashboard',<Dashboard/>],['/documents',<Documents/>],['/chat',<Chat/>],['/conversations',<History/>],['/profile',<Profile/>],['/admin',<Admin/>]].map(([p,c])=><Route key={p as string} path={p as string} element={<Protected><Shell>{c}</Shell></Protected>}/>) }<Route path="*" element={<Navigate to={loggedIn()?'/dashboard':'/login'} replace/>}/></Routes>}
